print("Compuerta OR")
print(False or False)
print(False or True)
print(True or False)
print(True or True)

print("\n compuerta AND")
print(False and False)
print(False and True)
print(True and False)
print(True and True)
